### ISSUE TITLE
Doesn't build on windows.

### ISSUE THREAD

**Issue by luckcolors** [addaleax/lzma-native#12] opened 2016-01-13 12:50 UTC
Hello lzma native it's not building on windows 64 unsing nodejs V.5.4.1.
Here is the debugging log:
```
5806 silly install lzma-native@0.5.0 C:\Users\luckcolors\Desktop\gamejolt\node_modules\.staging\lzma-native-3e2fea73d4586393475ade292442de78
5807 info lifecycle lzma-native@0.5.0~install: lzma-native@0.5.0
5808 verbose lifecycle lzma-native@0.5.0~install: unsafe-perm in lifecycle true
5809 verbose lifecycle lzma-native@0.5.0~install: PATH: D:\DevTools\nvm\v5.4.1\node_modules\npm\bin\node-gyp-bin;C:\Users\luckcolors\Desktop\gamejolt\node_modules\lzma-native\node_modules\.bin;C:\Users\luckcolors\Desktop\gamejolt\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Skype\Phone\;C:\Windows\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;D:\DevTools\Git\cmd;D:\DevTools\nvm;D:\DevTools\nodejs;C:\Users\luckcolors\AppData\Roaming\npm;D:\DevTools\nvm;D:\DevTools\nodejs;D:\DevTools\wget;D:\DevTools\Git\cmd;D:\DevTools\youtube-dl;D:\DevTools\ffmpeg\bin;D:\DevTools\Sloppy;D:\DevTools\wpull
5810 verbose lifecycle lzma-native@0.5.0~install: CWD: C:\Users\luckcolors\Desktop\gamejolt\node_modules\lzma-native
5811 silly lifecycle lzma-native@0.5.0~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
5812 silly lifecycle lzma-native@0.5.0~install: Returned: code: 1  signal: null
5813 info lifecycle lzma-native@0.5.0~install: Failed to exec install script
5814 verbose unlock done using C:\Users\luckcolors\AppData\Roaming\npm-cache\_locks\staging-0ee51277284de0f6.lock for C:\Users\luckcolors\Desktop\gamejolt\node_modules\.staging
5815 silly rollbackFailedOptional Starting
5816 silly rollbackFailedOptional Finishing
5817 silly runTopLevelLifecycles Starting
5818 silly runTopLevelLifecycles Finishing
5819 silly install printInstalled
5820 warn EPACKAGEJSON game-jolt@0.2.0 No repository field.
5821 warn EPACKAGEJSON game-jolt@0.2.0 No license field.
5822 verbose stack Error: lzma-native@0.5.0 install: `node-gyp rebuild`
5822 verbose stack Exit status 1
5822 verbose stack     at EventEmitter.<anonymous> (D:\DevTools\nvm\v5.4.1\node_modules\npm\lib\utils\lifecycle.js:232:16)
5822 verbose stack     at emitTwo (events.js:87:13)
5822 verbose stack     at EventEmitter.emit (events.js:172:7)
5822 verbose stack     at ChildProcess.<anonymous> (D:\DevTools\nvm\v5.4.1\node_modules\npm\lib\utils\spawn.js:24:14)
5822 verbose stack     at emitTwo (events.js:87:13)
5822 verbose stack     at ChildProcess.emit (events.js:172:7)
5822 verbose stack     at maybeClose (internal/child_process.js:821:16)
5822 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
5823 verbose pkgid lzma-native@0.5.0
5824 verbose cwd C:\Users\luckcolors\Desktop\gamejolt
5825 error Windows_NT 10.0.10240
5826 error argv "D:\\DevTools\\nodejs\\node.exe" "D:\\DevTools\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
5827 error node v5.4.1
5828 error npm  v3.3.12
5829 error code ELIFECYCLE
5830 error lzma-native@0.5.0 install: `node-gyp rebuild`
5830 error Exit status 1
5831 error Failed at the lzma-native@0.5.0 install script 'node-gyp rebuild'.
5831 error Make sure you have the latest version of node.js and npm installed.
5831 error If you do, this is most likely a problem with the lzma-native package,
5831 error not with npm itself.
5831 error Tell the author that this fails on your system:
5831 error     node-gyp rebuild
5831 error You can get their info via:
5831 error     npm owner ls lzma-native
5831 error There is likely additional logging output above.
5832 verbose exit [ 1, true ]
```

**Comment by addaleax** [comment] 2016-01-13 13:09
Thanks for the report! Two things: Firstly, could you try and update your version of lzma-native to 1.x.x? The API is almost unchanged, but not the build system; And secondly, would you mind uploading your npm-debug.log somewhere? It should contain the relevant information for debugging this.

**Comment by addaleax** [comment] 2016-01-13 13:31
(If you don’t feel comfortable uploading the log, that’s perfectly fine, but I feel like there’s not much to debug with in your excerpt)

**Comment by luckcolors** [comment] 2016-01-13 18:43
Oh No it's totally fine  :).
it's just i didn't upload it at first becuase i'm building the https://github.com/gamejolt/gamejolt
frontend so the log was very long. 
I re runned npm install.
Here's the log:
[npm-debug.zip](https://github.com/addaleax/lzma-native/files/89343/npm-debug.zip).

**Comment by addaleax** [comment] 2016-01-14 09:59
Ok, yeah, the log does not say a lot more (except that everything before `node-gyp rebuild` works fine). What you can do is:

* Update `lzma-native` in your package.json to 1.0.3 (or, better, ^1.0.3). Since v1.0.0, the project uses [node-pre-gyp](https://github.com/mapbox/node-pre-gyp) to provide *precompiled* binaries for many systems and node versions (including yours), effectively removing the need to compile the library from scratch in many cases (and speeding up the installation *a lot*).
* Make sure that `node-gyp` is in your `%PATH%`, esp. maybe look in `D:\DevTools\nvm\v5.4.1\node_modules\npm\bin\node-gyp-bin`… there should be some kind of executable with that name in there, I guess?
* Verify that you can execute `node-gyp` on the command line. It should come with every Node.js installation, so if that fails, chances are the problem is outside the scope of this module.

There’s also the infamous nodejs/node-gyp#629 thread, but it does not seem to be the relevant issue for this particular thing, since there’s no debug output from node-gyp included here, implying that it might not have gotten that far.

**Comment by addaleax** [comment] 2016-01-14 10:40
And btw, I’ll try this out on Windows anytime soon, but unfortunately I don’t have regular access to Windows machines and I’m more or less relying on AppVeyor to check the Windows builds so far…

**Comment by luckcolors** [comment] 2016-01-14 13:27
Ok i didn't had node-gyp and node-pre-gyp install so i installed them
Building lzma-native alone works so there must be some dependency wchich requires the old one.
Thanks for your help :).

**Comment by addaleax** [comment] 2016-01-14 13:36
Okay, I’ll close this here and add some info at the issue you just opened :)

**Closed by addaleax** 2016-01-14 13:36 UTC
